# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://raw.githubusercontent.com/okta/okta-management-openapi-spec/refs/heads/master/dist/2024.08.3/management-minimal.yaml
spec: oas3
envPrefix: OKTA
patchBefore:
  - path: patch-before.yaml
    strategy: json6902
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
