# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://apinext.collegefootballdata.com/api-docs.json
spec: oas3
envPrefix: CFBD_V2
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
