services:
  ndc-http:
    image: ghcr.io/hasura/ndc-http:${NDC_HTTP_VERSION:-v0.8.0}
    ports:
      - 8080:8080
    volumes:
      - ./schema:/etc/connector:ro
    environment:
      SENDGRID_SERVER_URL: http://sendgrid-mock:3000
      SENDGRID_API_KEY: sendgrid-api-key
      HASURA_LOG_LEVEL: debug

  sendgrid-mock:
    image: ghashange/sendgrid-mock:1.12.0
    ports:
      - "3000"
    environment:
      API_KEY: sendgrid-api-key
