# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions-next/ghes-3.15/ghes-3.15.json
spec: oas3
envPrefix: GITHUB
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
