# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://raw.githubusercontent.com/sendgrid/sendgrid-oai/refs/tags/1.9.1/oai.json
spec: oas2
envPrefix: SENDGRID
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
