files:
  - file: twilio_accounts_v1.json
    spec: ndc
  - file: twilio_assistants_v1.json
    spec: ndc
  - file: twilio_bulkexports_v1.json
    spec: ndc
  - file: twilio_chat_v3.json
    spec: ndc
  - file: twilio_content_v2.json
    spec: ndc
  - file: twilio_conversations_v1.json
    spec: ndc
  - file: twilio_events_v1.json
    spec: ndc
  - file: twilio_flex_v2.json
    spec: ndc
  - file: twilio_frontline_v1.json
    spec: ndc
  - file: twilio_iam_organizations.json
    spec: ndc
  - file: twilio_iam_v1.json
    spec: ndc
  - file: twilio_insights_v2.json
    spec: ndc
  - file: twilio_intelligence_v2.json
    spec: ndc
  - file: twilio_ip_messaging_v2.json
    spec: ndc
  - file: twilio_lookups_v2.json
    spec: ndc
  - file: twilio_marketplace_v1.json
    spec: ndc
  - file: twilio_messaging_v1.json
    spec: ndc
  - file: twilio_microvisor_v1.json
    spec: ndc
  - file: twilio_monitor_v1.json
    spec: ndc
  - file: twilio_notify_v1.json
    spec: ndc
  - file: twilio_numbers_v2.json
    spec: ndc
  - file: twilio_oauth_v1.json
    spec: ndc
  - file: twilio_preview.json
    spec: ndc
  - file: twilio_pricing_v2.json
    spec: ndc
  - file: twilio_proxy_v1.json
    spec: ndc
  - file: twilio_routes_v2.json
    spec: ndc
  - file: twilio_serverless_v1.json
    spec: ndc
  - file: twilio_studio_v2.json
    spec: ndc
  - file: twilio_supersim_v1.json
    spec: ndc
  - file: twilio_sync_v1.json
    spec: ndc
  - file: twilio_taskrouter_v1.json
    spec: ndc
  - file: twilio_trunking_v1.json
    spec: ndc
  - file: twilio_trusthub_v1.json
    spec: ndc
  - file: twilio_verify_v2.json
    spec: ndc
  - file: twilio_video_v1.json
    spec: ndc
  - file: twilio_voice_v1.json
    spec: ndc
  - file: twilio_wireless_v1.json
    spec: ndc
  - file: twilio_api_v2010.json
    spec: ndc
