services:
  ndc-http:
    image: ghcr.io/hasura/ndc-http:${NDC_HTTP_VERSION:-v0.8.0}
    ports:
      - 8080:8080
    volumes:
      - ./schema:/etc/connector:ro
    environment:
      HASURA_LOG_LEVEL: debug
