# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/configuration.schema.json
strict: true
forwardHeaders:
  enabled: false
  argumentField: headers
  responseHeaders: null
concurrency:
  query: 1
  mutation: 1
  http: 1
files:
  - file: billing_subscriptions_v1.json
    spec: ndc
  - file: catalogs_products_v1.json
    spec: ndc
  - file: checkout_orders_v1.json
    spec: ndc
  - file: checkout_orders_v2.json
    spec: ndc
  - file: customer_disputes_v1.json
    spec: ndc
  - file: customer_partner_referrals_v1.json
    spec: ndc
  - file: customer_partner_referrals_v2.json
    spec: ndc
  - file: invoicing_v1.json
    spec: ndc
  - file: invoicing_v2.json
    spec: ndc
  - file: notifications_webhooks_v1.json
    spec: ndc
  - file: payment-experience_web_experience_profiles_v1.json
    spec: ndc
  - file: payments_payment_v1.json
    spec: ndc
  - file: payments_payment_v2.json
    spec: ndc
  - file: payments_payouts_batch_v1.json
    spec: ndc
  - file: reporting_transactions_v1.json
    spec: ndc
  - file: shipping_shipment_tracking_v1.json
    spec: ndc
  - file: vault_payment_tokens_v3.json
    spec: ndc
