# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://api.opensuse.org/apidocs/OBS-v2.10.50.yaml
spec: oas3
envPrefix: OBS
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
