# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://api.aucklandmuseum.com/apidoc
spec: oas2
envPrefix: AUCKLAND_MUSEUM
patchBefore:
  - path: patch-before.yaml
    strategy: json6902
