services:
  ndc-http:
    image: ghcr.io/hasura/ndc-http:${NDC_HTTP_VERSION:-v0.6.1}
    ports:
      - 8080:8080
    volumes:
      - ./schema:/etc/connector:ro
    environment:
      OPENAI_SERVER_URL: https://api.openai-mock.com/v1
      OPENAI_API_KEY_AUTH_TOKEN: sk-0
      HASURA_LOG_LEVEL: debug
