# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions-next/api.github.com/api.github.com.json
spec: oas3
envPrefix: GITHUB
patchBefore:
  - path: patch-before.yaml
    strategy: json6902
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
