# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://raw.githubusercontent.com/paypal/paypal-rest-api-specifications/refs/heads/main/openapi/customer_partner_referrals_v1.json
spec: oas3
envPrefix: PAYPAL
patchBefore:
  - path: patch-before.yaml
    strategy: json6902
