# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://raw.githubusercontent.com/twilio/sendgrid-oai/refs/heads/main/spec/json/tsg_suppressions_v3.json
spec: oas3
envPrefix: SENDGRID
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
