# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/configuration.schema.json
strict: true
forwardHeaders:
  enabled: true
  argumentField: headers
  responseHeaders: null
concurrency:
  query: 1
  mutation: 1
  http: 1
files:
  - file: idp.json
    spec: ndc
  - file: oauth.json
    spec: ndc
    patchAfter:
      - path: patches/patch-oauth.yaml
        strategy: json6902
