services:
  ndc-http:
    image: ghcr.io/hasura/ndc-http:${NDC_HTTP_VERSION:-v0.7.0}
    ports:
      - 8080:8080
    volumes:
      - ./schema:/etc/connector:ro
    environment:
      # OKTA_SERVER_URL: http://mock-idp:4010
      # OKTA_OAUTH_SERVER_URL: http://mock-oauth:4010
      # OKTA_CLIENT_AUTHENTICATION_CLIENT_SECRET_BASIC_USERNAME: user
      # OKTA_CLIENT_AUTHENTICATION_CLIENT_SECRET_BASIC_PASSWORD: password
      HASURA_LOG_LEVEL: debug

  mock-api:
    image: stoplight/prism:5.12.1
    command: "mock -h 0.0.0.0 https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions/api.github.com/api.github.com.json"
    ports:
      - "4010"
