services:
  ndc-http:
    image: ghcr.io/hasura/ndc-http:${NDC_HTTP_VERSION:-v0.6.0}
    ports:
      - 8080:8080
    volumes:
      - ./schema:/etc/connector:ro
    environment:
      CFBD_API_KEY: ${CFBD_API_KEY}
      HASURA_LOG_LEVEL: debug
