# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: ./asana_oas.yaml
spec: oas3
envPrefix: ASANA
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
