# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-http/refs/heads/main/ndc-http-schema/jsonschema/convert-config.schema.json
file: https://raw.githubusercontent.com/Asana/openapi/7d1d65782705d07a0214ac5a2651b15449c680d9/defs/asana_oas.yaml
spec: oas3
envPrefix: ASANA
patchAfter:
  - path: patch-after.yaml
    strategy: json6902
